//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreRequest
    {
        public int RequestId { get; set; }
        public string StoreId { get; set; }
        public string PublisherId { get; set; }
        public string TitleId { get; set; }
        public string RequestDetails { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
    
        public virtual publisher publisher { get; set; }
        public virtual store store { get; set; }
        public virtual title title { get; set; }
    }
}
